### ISSUE TITLE
Integrate with FIA-API

### ISSUE THREAD

**Issue by keiranjprice101** [fiaisis/admin-portal#3]
- Integrate the PUT endpoint below, and either of the GET endpoints
- Consider streamlining the existing logic (remove redundancy) by editing FIAAPI to return a list of instrument names (only) for the first endpoint, and implement all 3 

  
  - GET [/instrument] Get Instruments
  
  - GET [/instrument/{instrument_name}/specification] : Get Instrument Specification
  
  - PUT[/instrument/{instrument_name}/specification] : Update Instrument Specification

- Replace mock data in `instruments.tsx` with the real instrument list (from fia api)

- Populate the code editor with the API returned specification file 

- On clicking the submit button it should carry out a PUT request to update the specification file, and update the snackbar/alert UI element with a human readable response status

**Comment by HumzahJavid** [comment]
Following difficulties with local / docker setup (and some intensive meetings), which has resulted in a local conda forge (backed by mamba) install. The next steps are to integrate the api (see description)
